set terminal png size 1000,600 enhanced font "Helvetica,12"
set output '../wykresy/sirz.png'
set title "Wszystkie grupy: podatni (S), chorzy (I), odporni (R), oraz liczby nowych zachorowań (Z)"
set xlabel "Dzień"
set ylabel "Liczba osobników w poszczególnych grupach"
set xrange [0:]
set yrange [0:]

plot "../dane/s.dat" using 1:2:3 with errorbars title "S średnia +/- odchylenie standardowe" lt rgb "orange", "../dane/i.dat" using 1:2:3 with errorbars title "I średnia +/- odchylenie standardowe" lt rgb "red", "../dane/r.dat" using 1:2:3 with errorbars title "R średnia +/- odchylenie standardowe" lt rgb "green", "../dane/z.dat" using 1:2:3 with errorbars title "Z średnia +/- odchylenie standardowe" lt rgb "blue"
